name: test

on:
  pull_request:
    types: [opened, synchronize]

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.os }}-node-${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16, 18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        working-directory: tests
        run: npm run test
